name: Continuous Deployment CD
on:
  push:
    branches:
      - main
    paths:
      - 'GITOPS/**'
      - '.github/workflows/cd.yml'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gitops:${{ github.sha }},${{ secrets.DOCKER_USERNAME }}/gitops:latest

      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          sudo mv kustomize /usr/local/bin/
      - name: Verificar versão instalada
        run: kustomize version

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
      - name: Verificar versão kubectl
        run: kubectl version --client

      - name: Update Kustomization with new image tag
        run: |
          cd k8s
          kustomize edit set image goserver=${{ secrets.DOCKER_USERNAME }}/gitops:${{ github.sha }}
          cd ../..

      - name: Commit and push changes to Kustomization
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add k8s/kustomization.yaml
          git commit -m "Update image tag to ${{ github.sha }}" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/HarolGyver/gitops.git main

      - name: Aplicar Kustomize
        run: kustomize build k8s | kubectl apply -f -